### ISSUE TITLE
fully nest replies and inputs?

### ISSUE THREAD

**Issue by dmajoraddnine** [elsehow/hyperchat2#13]
It took me a while to figure out why the indentation was bugging me -- I realized that I expect replies to be fully left-indented in accordance with their nesting.  IMHO it's a little confusing to have all replies nested at same level:

![chat-snip-2](https://cloud.githubusercontent.com/assets/1085461/13763369/03bb70b0-ea1c-11e5-8ebf-5888a3c73846.PNG)

At the least I'd say you would want to indent the nested input to match the nested replies.

**Comment by elsehow** [comment]
AH!! thank you. willfix

**Comment by elsehow** [comment]
fixed cf985d67e79e9323bb659f6c5da4deeba5016338
